export const LOGIN_ACTION = "LOGIN_ACTION";
export const SET_INFO_USER = "SET_INFO_USER";
export const SET_BOOK_TICKET_USER = "SET_BOOK_TICKET_USER";
export const SET_USER_LIST = "SET_USER_LIST";
export const GET_TOKEN_ACTION = "GET_TOKEN_ACTION";
export const SET_INFO_USER_BY_USERNAME = "SET_INFO_USER_BY_USERNAME";
