export const SET_LIST_FILM = "SET_LIST_FILM";
export const SET_FILM_NOW_PLAYING = "SET_FILM_NOW_PLAYING";
export const SET_FILM_COMMING_SOON = "SET_FILM_COMMING_SOON";
export const SET_INFO_FILM = "SET_INFO_FILM";
export const REMOVE_FILM = "REMOVE_FILM";
