export const SET_DETAIL_TICKET_ROOM = "SET_DETAIL_TICKET_ROOM";
export const BOOK_TICKET = "BOOK_TICKET";
export const BOOK_TICKET_COMPLETE = "BOOK_TICKET_COMPLETE";

export const CHANGE_TAB = " CHANGE_TAB";
